package com.dicoding.asclepius.utils


const val IMAGE_URI_EXTRA = "IMAGE_URI_EXTRA"
const val FIRST_LABEL_RESULT_EXTRA = "FIRST_LABEL_RESULT_EXTRA"
const val FIRST_SCORE_RESULT_EXTRA = "FIRST_SCORE_RESULT_EXTRA"
const val SECOND_LABEL_RESULT_EXTRA = "SECOND_LABEL_RESULT_EXTRA"
const val SECOND_SCORE_RESULT_EXTRA = "SECOND_SCORE_RESULT_EXTRA"
const val IMAGE_CLASSIFIER_HELPER_TAG = "ImageClassifierHelper"
const val NEWS_LANGUAGE = "en"
const val NEWS_CATEGORY = "health"
const val NEWS_QUERY = "Cancer"